# Generated by Django 5.0.6 on 2024-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('has_test', models.BooleanField()),
                ('response_letter_required', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('is_open', models.BooleanField()),
                ('address', models.TextField()),
                ('url', models.URLField()),
                ('employer', models.URLField()),
            ],
        ),
    ]
