# Generated by Django 5.0.6 on 2024-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_or_release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='area',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.TextField(default=''),
        ),
    ]
