# Generated by Django 5.0.6 on 2024-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_or_release', '0002_vacancy_area_vacancy_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.TextField(),
        ),
    ]
